# Generated by Django 4.0.2 on 2022-02-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_slider_status_alter_product_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
